---
title: "NLP Week 1 Assignment"
author: "Nicole Serino"
date: "`r format(Sys.Date(), '%B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true 
    toc_depth: 1
    css: !expr here::here("../StylesTemplates/NS.css")
---

```{r setup, include=F}
knitr::opts_chunk$set(fig.width=8, fig.height=5, fig.align = 'left', fig.path='Figs/', cache.path='Cache/', eval=T, echo=T, tidy=TRUE,  cache=F, message=F, warning=F, stringsAsFactors=F, yaml.eval.expr = TRUE)  

library(xfun)
pkg_attach("tidyverse", "here", "kableExtra", "RCurl", "psych", "knitr", "RColorBrewer", 'dplyr', install=T)

jamie.theme <- theme_bw() + theme(axis.line = element_line(colour = "#000000"), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_blank(), panel.background = element_blank(), legend.title= element_blank())  #custom theme ggplot2

print.me <- function(x, ...) {
if (nrow(x) > 200){
   len <- 200 
    } else {
       len <- (nrow(x))
}
   x[1:len,] %>%
   kbl(digits=2, align= 'l', booktabs=T) %>%
   kable_styling(fixed_thead = T) %>%
   kable_paper("striped", full_width = T, html_font = "Helvetica", font_size = 12) %>%
   row_spec(0, color = "white", background = "#5b705f", font_size = 12) %>%
   scroll_box(width = "700px", height = "500px") %>%
   asis_output()
}

registerS3method("knit_print", "data.frame", print.me)
#to_R <- read.csv(here("data", "MyRaw.txt")) ---- using 'here' to read in data
```

#My First Homework
I am going to produce a string called mary had a little lamb in one code block. Then, I am going to split the string to one word per row. Then I am going to add a variable called Nletters that counts the letters in each word. Tailor CSS to fit my personal needs. 

```{r}
#Produce a string called mary had a little lamb
My_string <- 'Mary Had A Little Lamb'
print(My_string)

#Split data using space as the delimiter
words <- unlist(strsplit(My_string, " "))
print(words)

#Convert into a tibble (data frame), each word becomes its own row
word_tbl <- tibble(word = words)
print(word_tbl)

#Count letters in each row
Nletters<- word_tbl %>%
mutate(Nletters = nchar(word))
print(Nletters)

```

